# Decision Tree

## Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.model_selection import train_test_split

In [40]:
from sklearn.tree import DecisionTreeRegressor,export_text,plot_tree

## Importing the data set

In [3]:
dataset = pd.read_csv("petrol_consumption.csv")

In [4]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [5]:
dataset.head()

Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.0            3571            1976                         0.525   
1         9.0            4092            1250                         0.572   
2         9.0            3865            1586                         0.580   
3         7.5            4870            2351                         0.529   
4         8.0            4399             431                         0.544   

   Petrol_Consumption  
0                 541  
1                 524  
2                 561  
3                 414  
4                 410

In [6]:
print(x)

[[9.0000e+00 3.5710e+03 1.9760e+03 5.2500e-01]
 [9.0000e+00 4.0920e+03 1.2500e+03 5.7200e-01]
 [9.0000e+00 3.8650e+03 1.5860e+03 5.8000e-01]
 [7.5000e+00 4.8700e+03 2.3510e+03 5.2900e-01]
 [8.0000e+00 4.3990e+03 4.3100e+02 5.4400e-01]
 [1.0000e+01 5.3420e+03 1.3330e+03 5.7100e-01]
 [8.0000e+00 5.3190e+03 1.1868e+04 4.5100e-01]
 [8.0000e+00 5.1260e+03 2.1380e+03 5.5300e-01]
 [8.0000e+00 4.4470e+03 8.5770e+03 5.2900e-01]
 [7.0000e+00 4.5120e+03 8.5070e+03 5.5200e-01]
 [8.0000e+00 4.3910e+03 5.9390e+03 5.3000e-01]
 [7.5000e+00 5.1260e+03 1.4186e+04 5.2500e-01]
 [7.0000e+00 4.8170e+03 6.9300e+03 5.7400e-01]
 [7.0000e+00 4.2070e+03 6.5800e+03 5.4500e-01]
 [7.0000e+00 4.3320e+03 8.1590e+03 6.0800e-01]
 [7.0000e+00 4.3180e+03 1.0340e+04 5.8600e-01]
 [7.0000e+00 4.2060e+03 8.5080e+03 5.7200e-01]
 [7.0000e+00 3.7180e+03 4.7250e+03 5.4000e-01]
 [7.0000e+00 4.7160e+03 5.9150e+03 7.2400e-01]
 [8.5000e+00 4.3410e+03 6.0100e+03 6.7700e-01]
 [7.0000e+00 4.5930e+03 7.8340e+03 6.6300e-01]
 [8.0000e+00 

In [7]:
print(y)

[541 524 561 414 410 457 344 467 464 498 580 471 525 508 566 635 603 714
 865 640 649 540 464 547 460 566 577 631 574 534 571 554 577 628 487 644
 640 704 648 968 587 699 632 591 782 510 610 524]


## Splitting the dataset into the Training set and Test set

In [8]:
x_train,x_test,y_train,y_test =  train_test_split(x,y, test_size = 0.2, random_state = 0)

## Training the Decision Tree Regression model on the training dataset

In [11]:
regressor  = DecisionTreeRegressor()
regressor.fit(x_train,y_train)

DecisionTreeRegressor()

## Predict Test Result

In [20]:
y_predict = regressor.predict(x_test)


In [23]:
df=pd.DataFrame({'Actual':y_test, 'Predicted':y_predict, 'diffrence' : y_test - y_predict})
df

Actual  Predicted  diffrence
0     534      541.0       -7.0
1     410      414.0       -4.0
2     577      574.0        3.0
3     571      554.0       17.0
4     577      631.0      -54.0
5     704      644.0       60.0
6     487      628.0     -141.0
7     587      649.0      -62.0
8     467      414.0       53.0
9     580      510.0       70.0

## Visualising the Decision Tree Regression result

In [38]:
text_representation = export_text(regressor)
print(text_representation)

|--- feature_3 <= 0.67
|   |--- feature_1 <= 4389.50
|   |   |--- feature_0 <= 8.75
|   |   |   |--- feature_2 <= 5350.00
|   |   |   |   |--- feature_1 <= 3731.50
|   |   |   |   |   |--- feature_1 <= 3645.50
|   |   |   |   |   |   |--- feature_3 <= 0.60
|   |   |   |   |   |   |   |--- value: [628.00]
|   |   |   |   |   |   |--- feature_3 >  0.60
|   |   |   |   |   |   |   |--- value: [648.00]
|   |   |   |   |   |--- feature_1 >  3645.50
|   |   |   |   |   |   |--- feature_3 <= 0.55
|   |   |   |   |   |   |   |--- value: [714.00]
|   |   |   |   |   |   |--- feature_3 >  0.55
|   |   |   |   |   |   |   |--- value: [699.00]
|   |   |   |   |--- feature_1 >  3731.50
|   |   |   |   |   |--- feature_1 <= 4298.00
|   |   |   |   |   |   |--- feature_1 <= 4020.50
|   |   |   |   |   |   |   |--- value: [591.00]
|   |   |   |   |   |   |--- feature_1 >  4020.50
|   |   |   |   |   |   |   |--- value: [610.00]
|   |   |   |   |   |--- feature_1 >  4298.00
|   |   |   |   |   |   |---

## Evaluating the Algorithm

In [25]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_predict))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_predict))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_predict)))

Mean Absolute Error: 47.1
Mean Squared Error: 3831.3
Root Mean Squared Error: 61.89749591057784
